### ISSUE TITLE
Number widget is typed as string

### ISSUE THREAD

**Issue by erikhofer** [jsaari97/netlify-ts#1]
Hey, first of all, this is a very nice library!

If I define a field with `widget: "number"`, the generated type for this field is a `string`. Is there a reasoning behind this or could this be changed to `number`?

**Comment by jsaari97** [comment]
Hello, thanks for checking out this library!

To save a `number` widget as a number, make sure you have defined the `value_type` option as either `int` or `float`, otherwise is saves the value as a string.

From Netlify CMS documentation:

> `value_type`: accepts `int` or `float`; any other value results in saving as a string

**Comment by erikhofer** [comment]
@jsaari97 Ah, I see. Thanks for the answer :)
