### ISSUE TITLE
Sync version?

### ISSUE THREAD

**Issue by mmkal** [jsaari97/netlify-ts#2]
For situations when promises aren't supported (for example, inside an eslint rule), would you be open to a `netlifyTs.sync(...)` function? It seems like it's only the filesystem-reading that relies on promises, and those APIs have sync equivalents too. I'd be happy to put up a PR if so.

**Comment by jsaari97** [comment]
Good catch! Refactored the code and added both `createNetlifyTypes` and `createNetlifyTypesAsync` functions in the `v1.1.0` release to support both use-cases.
