### ISSUE TITLE
Transform breaks if field name isn't Capitalized

### ISSUE THREAD

**Issue by zanami** [jsaari97/netlify-ts#4]
also it fails if field name is something like 'large_video'

in transform.js

```
const pattern = new RegExp(`(${typeNames.map((w) => `${name}_${w}`).join("|")}) {`);
```
here's my regexp
`/(Post_Slice_Hero|Post_Slice_editor|Post_Slice_large_video) {/`

and here's what pattern.test runs against (for example)

`'interface Page_Slice_LargeVideo { title: string; description?: string; media: any; poster?: string; }',`

so 'rest' and 'interfaces' arrays get messed up and types eventually are broken

UPD: some more info

I believe it happens only to "[typed lists](https://github.com/jsaari97/netlify-ts/blob/e821f69d695e34476ec84f57e23484cfb5bcb019/src/widget/transform.ts#L140)" when label is used to set widgetName [here](https://github.com/jsaari97/netlify-ts/blob/e821f69d695e34476ec84f57e23484cfb5bcb019/src/widget/transform.ts#L73)

I'll have to disable labels anyways as they are less permanent and robust.

Thanks for a great module BTW. I wonder why it's not more popular. It would be great to have a way to parse a js object instead of config.yml to use with [manual init ](https://www.netlifycms.org/docs/beta-features/#manual-initialization).

**Comment by jsaari97** [comment]
Hi, thanks for the bug report! This issue should be resolved in version `v1.2.1`.

Feel free to re-open this issue if the problem persists!
