### ISSUE TITLE
CLI Output Path Not Working

### ISSUE THREAD

**Issue by jsongo21** [jsaari97/netlify-ts#5]
Hi having problems with the file output  location of the types file
When I'm running on the CLI, the output argument will always use the default value of `netlify-types.ts`

## Expected Behavior

 ` netlify-ts public/admin/config.yml src/my-types.ts` outputs a file to `src/my-types.ts`
 
## Current Behavior

 ` netlify-ts public/admin/config.yml src/my-types.ts` outputs a file to `netlify-types.ts`

## Context (Environment)

WSL2 Ubuntu on windows 11
npm 6.13.15
node 14.17.6

**Comment by jsaari97** [comment]
Hello, thanks for the bug report! This should now be resolved in the latest version 🎉  (`v1.2.2`)
